Updates
yoshuawuyts/wstd pull request #2
Opened 2024-09-19 15:57 UTC by calvinrp

- add a `read_all()` for the incoming body
- `IntoUrl` trait
- `Headers` is now an alias of the type from `wasi` crate
- `Request` can now set the HTTP `Headers`

2024-09-19 17:38 UTC, yoshuawuyts requested changes
Two minor changes - but overall this looks good. Thank you!

2024-09-19 17:38 UTC, yoshuawuyts commented on src/http/client.rs
>      }
Can we remove this? I understand this comes in handy when testing, but if we add this for the `Get` method we will want to add it for more methods too - and that ends up adding additional API surface.

2024-09-19 17:38 UTC, yoshuawuyts commented on src/http/response.rs
> +    }
Ohh yeah, this is neat! - Reading the entire body into a vec is a common pattern.

Fhis would probably be a good fit to generalize as part of `wstd::io::Read` trait as an async dual to [`std::io::Read::read_to_end`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_end). Could you add this there instead? That way all other types can reuse this functionality, as long as they implement the `Read` trait.

2024-09-20 17:18 UTC, closed without merging

2024-09-20 17:18 UTC, calvinrp commented
Revising and following up with multiple PRs.